name: Calicut_compass
description: An android app that includes some really cool aspects about kozhikode with pretty helpful services.The app is under development

# Specify Flutter SDK version
environment:
  sdk: ">=3.0.0 <4.0.0" # Use your Flutter SDK version

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # iOS style icons
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  google_maps_flutter: ^2.5.3
  intl: ^0.19.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0 # For handling coordinates
  geolocator: ^10.1.0
  url_launcher: # For user location
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  google_nav_bar:
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # For code linting

# Flutter specific configurations
flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  image_path: "assets/images/icon.png"    # Path to your icon file