name: your_app_name
description: A new Flutter project.

# Specify Flutter SDK version
environment:
  sdk: ">=3.0.0 <4.0.0" # Use your Flutter SDK version

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # iOS style icons
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  google_maps_flutter: ^2.5.3
  intl: ^0.19.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0 # For handling coordinates
  geolocator: ^10.1.0
  url_launcher: # For user location
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  google_nav_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # For code linting

# Flutter specific configurations
flutter:
  uses-material-design: true
  assets:
    - assets/images/
